### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by tperelle** [posixx/home_assistant_custom_envoy#5]
Hello, 

I have a Enphase Metered-S installed few days aga, with the last system version. 
I generated a token with Enphase web tools.

I installed you integration but I can't configure it and I don't understand why. 
I tried configuring it using: 
- "envoy" username and blank password
- enphase username/password
- enphase username/token
- with the enlighten checkbox checked and unchecked

But in the best case I get an expected error. 

Can you explain clearly what it is expected in each form field ?
Can the fact that I have already generated a token be a problem?

Thanks for your help

**Comment by Casadomoticap** [comment]
Hi, with enphase custom components you need to put:

- username: your emaiil of your Enphase account (the same email that you use to enter to the App)
- password: the password of your Enphase account
- Serial number of your envoy should be automatic filled with the custom repostory
- Checked the enlighten checbox

Try this

**Comment by tperelle** [comment]
It is with this configuration I got the unexpected error. But this time it passed, curious...
But thanks for you answer

**Comment by RoadXY** [comment]
Could you please choose the issue then?
Thanks

**Comment by jfhmolina** [comment]
Hi,
I have the same problem, unexpected error appears.

How have you solved it?
The envoy firmware is D7.0.88
I have tried with user: envoy and without a password, also with the passwords of the app... and nothing at all.
